USE `irsi`;

INSERT INTO `dim_currencies`
    (`code`, `name`, `symbol`)
VALUES
    ('EUR', 'Euro', '€');

INSERT INTO `dim_suppliers`
    (`id`, `name`, `url`)
VALUES
    (1, 'Property Services Regulatory Authority', 'https://www.psr.ie');

INSERT INTO `dim_postal_areas`
    (`routing_key`, `county`, `towns`)
VALUES
    ('A41', 'Dublin', JSON_ARRAY('Ballyboughal')),
    ('A42', 'Dublin', JSON_ARRAY('Garristown')),
    ('A45', 'Dublin', JSON_ARRAY('Oldtown')),
    ('A63', 'Wicklow', JSON_ARRAY('Delgany', 'Greystones', 'Kilcoole', 'Newcastle', 'Newtownmountkennedy')),
    ('A67', 'Wicklow', JSON_ARRAY('Rathnew', 'Wicklow')),
    ('A75', 'Monaghan', JSON_ARRAY('Ballybay', 'Castleblaney')),
    ('A81', 'Monaghan', JSON_ARRAY('Carrickmacross')),
    ('A82', 'Cavan', JSON_ARRAY('Kingscourt', 'Virginia')),
    ('A82', 'Meath', JSON_ARRAY('Kells')),
    ('A83', 'Meath', JSON_ARRAY('Enfield', 'Summerhill')),
    ('A84', 'Meath', JSON_ARRAY('Ashbourne')),
    ('A85', 'Meath', JSON_ARRAY('Dunshaughlin', 'Ratoath')),
    ('A86', 'Meath', JSON_ARRAY('Dunboyne')),
    ('A91', 'Louth', JSON_ARRAY('Dundalk')),
    ('A92', 'Louth', JSON_ARRAY('Ardee', 'Drogheda')),
    ('A92', 'Meath', JSON_ARRAY('Laytown', 'Bettystown', 'Mornington', 'Donacarney')),
    ('A94', 'Dublin', JSON_ARRAY('Blackrock', 'Booterstown', 'Monkstown')),
    ('A96', 'Dublin', JSON_ARRAY('Glenageary')),
    ('A98', 'Wicklow', JSON_ARRAY('Bray')),
    ('C15', 'Meath', JSON_ARRAY('Navan')),
    ('D01', 'Dublin', JSON_ARRAY('Dublin 1')),
    ('D02', 'Dublin', JSON_ARRAY('Dublin 2')),
    ('D03', 'Dublin', JSON_ARRAY('Dublin 3')),
    ('D04', 'Dublin', JSON_ARRAY('Dublin 4')),
    ('D05', 'Dublin', JSON_ARRAY('Dublin 5')),
    ('D06', 'Dublin', JSON_ARRAY('Dublin 6')),
    ('D07', 'Dublin', JSON_ARRAY('Dublin 7')),
    ('D08', 'Dublin', JSON_ARRAY('Dublin 8')),
    ('D09', 'Dublin', JSON_ARRAY('Dublin 9')),
    ('D10', 'Dublin', JSON_ARRAY('Dublin 10')),
    ('D11', 'Dublin', JSON_ARRAY('Dublin 11')),
    ('D12', 'Dublin', JSON_ARRAY('Dublin 12')),
    ('D13', 'Dublin', JSON_ARRAY('Dublin 13')),
    ('D14', 'Dublin', JSON_ARRAY('Dublin 14')),
    ('D15', 'Dublin', JSON_ARRAY('Dublin 15')),
    ('D16', 'Dublin', JSON_ARRAY('Dublin 16')),
    ('D17', 'Dublin', JSON_ARRAY('Dublin 17')),
    ('D18', 'Dublin', JSON_ARRAY('Dublin 18')),
    ('D20', 'Dublin', JSON_ARRAY('Dublin 20')),
    ('D22', 'Dublin', JSON_ARRAY('Dublin 22')),
    ('D24', 'Dublin', JSON_ARRAY('Dublin 24')),
    ('D6W', 'Dublin', JSON_ARRAY('Dublin 6W')),
    ('E21', 'Tipperary', JSON_ARRAY('Cahir')),
    ('E25', 'Tipperary', JSON_ARRAY('Cashel')),
    ('E32', 'Tipperary', JSON_ARRAY('Carrick-on-Suir')),
    ('E34', 'Tipperary', JSON_ARRAY('Tipperary')),
    ('E41', 'Tipperary', JSON_ARRAY('Thurles')),
    ('E45', 'Tipperary', JSON_ARRAY('Nenagh')),
    ('E53', 'Tipperary', JSON_ARRAY('Roscrea')),
    ('E91', 'Tipperary', JSON_ARRAY('Clonmel')),
    ('F12', 'Mayo', JSON_ARRAY('Claremorris')),
    ('F23', 'Mayo', JSON_ARRAY('Castlebar')),
    ('F26', 'Mayo', JSON_ARRAY('Ballina')),
    ('F28', 'Mayo', JSON_ARRAY('Westport')),
    ('F31', 'Mayo', JSON_ARRAY('Ballinrobe')),
    ('F35', 'Mayo', JSON_ARRAY('Ballyhaunis')),
    ('F42', 'Roscommon', JSON_ARRAY('Roscommon')),
    ('F45', 'Roscommon', JSON_ARRAY('Castlerea')),
    ('F52', 'Roscommon', JSON_ARRAY('Boyle')),
    ('F56', 'Sligo', JSON_ARRAY('Ballymote')),
    ('F91', 'Sligo', JSON_ARRAY('Sligo')),
    ('F92', 'Donegal', JSON_ARRAY('Letterkenny')),
    ('F93', 'Donegal', JSON_ARRAY('Lifford')),
    ('F94', 'Donegal', JSON_ARRAY('Donegal')),
    ('H12', 'Cavan', JSON_ARRAY('Cavan')),
    ('H14', 'Cavan', JSON_ARRAY('Belturbet')),
    ('H16', 'Cavan', JSON_ARRAY('Cootehill')),
    ('H18', 'Monaghan', JSON_ARRAY('Monaghan')),
    ('H23', 'Monaghan', JSON_ARRAY('Clones')),
    ('H53', 'Galway', JSON_ARRAY('Ballinasloe')),
    ('H54', 'Galway', JSON_ARRAY('Tuam')),
    ('H62', 'Galway', JSON_ARRAY('Loughrea')),
    ('H65', 'Galway', JSON_ARRAY('Athenry')),
    ('H71', 'Galway', JSON_ARRAY('Clifden')),
    ('H91', 'Galway', JSON_ARRAY('Galway')),
    ('K32', 'Dublin', JSON_ARRAY('Balbriggan')),
    ('K34', 'Dublin', JSON_ARRAY('Skerries')),
    ('K36', 'Dublin', JSON_ARRAY('Malahide')),
    ('K45', 'Dublin', JSON_ARRAY('Lusk')),
    ('K56', 'Dublin', JSON_ARRAY('Rush')),
    ('K67', 'Dublin', JSON_ARRAY('Swords', 'Dublin Airport')),
    ('K78', 'Dublin', JSON_ARRAY('Lucan')),
    ('N37', 'Westmeath', JSON_ARRAY('Athlone')),
    ('N39', 'Longford', JSON_ARRAY('Longford')),
    ('N41', 'Leitrim', JSON_ARRAY('Carrick-on-Shannon')),
    ('N91', 'Westmeath', JSON_ARRAY('Mullingar')),
    ('P12', 'Cork', JSON_ARRAY('Macroom')),
    ('P14', 'Cork', JSON_ARRAY('Crookstown')),
    ('P17', 'Cork', JSON_ARRAY('Kinsale')),
    ('P24', 'Cork', JSON_ARRAY('Cobh')),
    ('P25', 'Cork', JSON_ARRAY('Midleton')),
    ('P31', 'Cork', JSON_ARRAY('Ballincollig')),
    ('P32', 'Cork', JSON_ARRAY('Donoughmore')),
    ('P36', 'Cork', JSON_ARRAY('Youghal')),
    ('P43', 'Cork', JSON_ARRAY('Carrigaline')),
    ('P47', 'Cork', JSON_ARRAY('Dunmanway')),
    ('P51', 'Cork', JSON_ARRAY('Mallow')),
    ('P56', 'Cork', JSON_ARRAY('Charleville')),
    ('P61', 'Cork', JSON_ARRAY('Fermoy')),
    ('P67', 'Cork', JSON_ARRAY('Mitchelstown')),
    ('P72', 'Cork', JSON_ARRAY('Bandon')),
    ('P75', 'Cork', JSON_ARRAY('Bantry')),
    ('P81', 'Cork', JSON_ARRAY('Skibbereen')),
    ('P85', 'Cork', JSON_ARRAY('Clonakilty')),
    ('R14', 'Kildare', JSON_ARRAY('Athy')),
    ('R21', 'Carlow', JSON_ARRAY('Muine Bheag')),
    ('R32', 'Laois', JSON_ARRAY('Portlaoise')),
    ('R35', 'Offaly', JSON_ARRAY('Tullamore')),
    ('R42', 'Offaly', JSON_ARRAY('Birr')),
    ('R45', 'Offaly', JSON_ARRAY('Edenderry')),
    ('R51', 'Kildare', JSON_ARRAY('Kildare')),
    ('R56', 'Kildare', JSON_ARRAY('Curragh Camp')),
    ('R93', 'Carlow', JSON_ARRAY('Carlow')),
    ('R95', 'Kilkenny', JSON_ARRAY('Kilkenny')),
    ('T12', 'Cork', JSON_ARRAY('Cork (centre)', 'Cork (southside)', 'Passage West', 'Cork Airport')),
    ('T23', 'Cork', JSON_ARRAY('Cork (northside)', 'Blarney')),
    ('T34', 'Cork', JSON_ARRAY('Whitechurch')),
    ('T45', 'Cork', JSON_ARRAY('Little Island')),
    ('T56', 'Cork', JSON_ARRAY('Watergrasshill')),
    ('V14', 'Clare', JSON_ARRAY('Shannon')),
    ('V15', 'Clare', JSON_ARRAY('Kilrush')),
    ('V23', 'Kerry', JSON_ARRAY('Caherciveen')),
    ('V31', 'Kerry', JSON_ARRAY('Listowel')),
    ('V35', 'Limerick', JSON_ARRAY('Kilmallock')),
    ('V42', 'Limerick', JSON_ARRAY('Newcastle West')),
    ('V92', 'Kerry', JSON_ARRAY('Tralee')),
    ('V93', 'Kerry', JSON_ARRAY('Killarney')),
    ('V94', 'Limerick', JSON_ARRAY('Limerick')),
    ('V95', 'Clare', JSON_ARRAY('Ennis')),
    ('W12', 'Kildare', JSON_ARRAY('Newbridge')),
    ('W23', 'Kildare', JSON_ARRAY('Maynooth')),
    ('W34', 'Kildare', JSON_ARRAY('Monasterevin')),
    ('W91', 'Kildare', JSON_ARRAY('Naas')),
    ('X35', 'Waterford', JSON_ARRAY('Dungarvan')),
    ('X42', 'Waterford', JSON_ARRAY('Kilmacthomas')),
    ('X91', 'Waterford', JSON_ARRAY('Waterford')),
    ('Y14', 'Wicklow', JSON_ARRAY('Arklow')),
    ('Y21', 'Wexford', JSON_ARRAY('Enniscorthy')),
    ('Y25', 'Wexford', JSON_ARRAY('Gorey')),
    ('Y34', 'Wexford', JSON_ARRAY('New Ross')),
    ('Y35', 'Wexford', JSON_ARRAY('Wexford'));
