@startuml

!include <C4/C4_Context>
!include <tupadr3/devicons/java>
!include <tupadr3/devicons/mysql>
!include <tupadr3/devicons/redis>
!include <tupadr3/devicons2/apachekafka_original>
!include <tupadr3/govicons/world>

hide stereotype

skinparam padding 10

LAYOUT_LEFT_RIGHT()

Person_Ext(user, "User", "Authorized User", $sprite="person")

Enterprise_Boundary(org, "organization") {
  SystemQueue(kafka, "Kafka", "Kafka KRaft Cluster", $sprite="apachekafka_original")
  SystemDb(mysql, "MySQL", "MySQL InnoDB Cluster", $sprite="mysql")
  SystemDb(redis, "Redis", "Redis Cluster", $sprite="redis")

  Person(system_user, "System User", "Authorized System User", $sprite="robot")

  Boundary(services, "IRSI") {
    System(gateway, "Gateway", "Entry point for ingestion workflows", $sprite="java")
    System(fetcher, "Fetcher", "Fetches real state data from multiple providers", $sprite="java")
    System(dispatcher, "Dispatcher", "Coordinates workflows between services", $sprite="java")
    System(archiver, "Archiver", "Saves real state data to persistent storage", $sprite="java")
  }
}

System_Ext(psra, "PSRA", "Property Services Regulatory Authority", $sprite="world")

Rel(user, gateway, "Sends ingestion request")
Rel(system_user, gateway, "Periodically sends ingestion request for current month")
Rel(gateway, kafka, "Produces sales search requests")

Rel(kafka, dispatcher, "Consumes sales")
Rel(dispatcher, kafka, "Produces sales details request")

Rel(kafka, fetcher, "Consumes sales search and details requests")

Rel(fetcher, redis, "Checks rate-limiting on suppliers")

Rel(fetcher, psra, "Performs sales search and requests sales details")

Rel(fetcher, kafka, "Produces sales and properties")

Rel(kafka, archiver, "Consumes sales and properties")

Rel(archiver, mysql, "Upserts sales and properties")

@enduml
